name: upnp
version: 2.0.1
description: Universal Plugin and Play Host/Client
homepage: https://github.com/SpinlockLabs/upnp.dart
dependencies:
  xml: "^4.5.1"
  crypto: "^2.1.5"
environment:
  sdk: ">=2.0.0 <3.0.0"

